version: "3.9"
services:
  db:
    container_name: "hinggu-product-db"
    image: mysql:8.0.28
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hinggu-product
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d

  application:
    build:
      context: ../
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: "hinggu-product-application"
    restart: always
    ports:
      - "8003:8003"
    depends_on:
      - db
